import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Kevin's Navigating Menu</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" Kevin "}
        <a href="" style={{ color: "#87CEFA", textDecoration: "none" }}>
          
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signup" style={{ color: "#87CEFA", textDecoration: "none" }}>
            CreateAccountPage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/Signin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Landingpage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminhome" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminHomePage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/analyzeimages" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ImageDisplay
          </Link>
        </li>
        {/* Added ResetPasswordPage link */}
        <li style={{ marginBottom: "10px" }}>
          <Link to="/resetpassword" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ResetPasswordPage
          </Link>
        </li>
        {/* Added Mainpage link */}
        <li style={{ marginBottom: "10px" }}>
          <Link to="/home" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Mainpage
          </Link>
        </li>
      

      </ul>
    </div>
  );
};

export default Home;
